server:
  port: 8088

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: no9173
      filters: stat
      max-active: 30
      initial-size: 1
      max-wait: 1000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      connection-error-retry-attempts: 2


  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

mybatis:
  type-aliases-package: com.dc.sec_kill.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


redisdao:
  ip: localhost
  port: 6379

person:
  name: li
  age: 10
